
apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: index-app-hpa-memory 
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment 
    name: index-app-deployment
  minReplicas: 3
  maxReplicas: 10 
  metrics: 
  - type: Resource
    resource:
      name: memory 
      target:
        type: Utilization 
        averageValue: 50Mi 
