apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-app-deployment
  labels:
    app: index-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: index-app
  template:
    metadata:
      labels:
        app: index-app
    spec:
      containers:
      - name: index-app
        image: bungyan07/index-app:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: index-app-service
#  labels:
#    app: index-app
spec:
  selector:
   # matchLabels:
    app: index-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
